{{- $label := include "celestiaNode.baseLabel" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $label }}-files-env
  namespace: {{ include "celestiaNode.namespace" . }}
data:
  config.toml: |
  {{- tpl (.Files.Get "files/config.toml") $ | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $label }}-scripts-env
  namespace: {{ include "celestiaNode.namespace" . }}
data:
  set-token.sh: |
  {{- .Files.Get "files/scripts/set-token.sh" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $label }}-env
  namespace: {{ include "celestiaNode.namespace" . }}
data:
  CELESTIA_NODE_TYPE: "{{ .Values.config.type }}"
  CELESTIA_TOKEN_AUTH_LEVEL: "{{ .Values.config.tokenAuthLevel }}"
---
{{- if eq .Values.config.network "custom" }}
{{- $customInfo := .Values.config.customInfo | required "customInfo is required for custom network" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $label }}-env
  namespace: {{ include "celestiaNode.namespace" . }}
data:
  CELESTIA_CUSTOM: {{ .Values.config.chainId }}:{{ $customInfo }}
{{- end }}
