use astria_celestia_client::CelestiaHttpClient;

mod state;

// The tests are using a fixed jwt with admin permissions. This works because at
// the time of this writing the jwts generated by celestia are deterministic.
const TOKEN: &str = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJwdWJsaWMiLCJyZWFkIiwid3JpdGUiLCJhZG1pbiJdfQ.kUsWQbb-vwNnDzepvz2Dmt0FEd5XgEllWPSr1b__e_o";

pub fn make_client() -> CelestiaHttpClient {
    CelestiaHttpClient::builder()
        .bearer_token(TOKEN)
        .endpoint("http://astria-celestia-client-test.localdev.me:80/jsonrpc/")
        .build()
        .unwrap()
}
